apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-catalog-service
  namespace: movie-reco-system
  labels:
    app: movie-catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-catalog-service
  template:
    metadata:
      labels:
        app: movie-catalog-service
    spec:
      containers:
      - name: movie-catalog-service
        image: movie-catalog-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: movie-reco-config
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        - name: SPRING_APPLICATION_NAME
          value: moviecatalogservice
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: movie-reco-config
              key: SPRING_DATA_MONGODB_URI
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 45
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: movie-catalog-service
  namespace: movie-reco-system
spec:
  selector:
    app: movie-catalog-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP 